// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SearchMLML.Model
{
    public class ModelInput
    {
        [ColumnName("source"), LoadColumn(0)]
        public string Source { get; set; }


        [ColumnName("destination"), LoadColumn(1)]
        public string Destination { get; set; }


    }
}
